Repository modern-agile-team/8term-mini-back, pull requests merged in 2024-08, with the labels that each got.

#4 Setting/GitHub template/#3
  .gitignore
  app/package-lock.json
Labels: setting

#6 데이터베이스 연결 완료됬습니다.
  app/app.js
  app/bin/www.js
  app/package-lock.json
  app/package.json
  app/src/config/db.js
  app/src/routes/home/home.ctrl.js
  app/src/routes/home/index.js
Labels: db

#12 메인페이지 get/ movies 요청 pr 올립니다.
  app/src/routes/home/home.ctrl.js
  app/src/routes/home/index.js
  app/src/routes/movie/movie.ctrl.js
  app/src/services/Movie.js
Labels: feature

#16 feature/movieStorage작성 & 이전 movie컨트롤러 코드 및 파일 제거/#15
  app/src/models/movieStorage.js
  app/src/routes/home/home.ctrl.js
  app/src/routes/home/index.js
  app/src/routes/movie/movie.ctrl.js
Labels: feature

#22 movie 조회 관련 API 리펙토링 입니다.
  app/src/config/db.js
  app/src/models/movieStorage.js
  app/src/models/reviewStorage.js
  app/src/routes/home/index.js
  app/src/routes/movieInfo/movieInfo.ctrl.js
  app/src/services/movie.js
Labels: modify

#25 Feature/review API 구현/#21
  app/app.js
  app/package.json
  app/src/models/reviewStorage.js
  app/src/routes/home/index.js
  app/src/routes/reviewInfo/reviewInfo.ctrl.js
  app/src/services/review.js
Labels: feature

#34 Feature/wish lists api/#23
  app/src/models/wishListStorage.js
  app/src/routes/home/index.js
  app/src/routes/movieInfo/movieInfo.ctrl.js
  app/src/routes/wishList/wishList.ctrl.js
  app/src/services/movie.js
  app/src/services/wishList.js
Labels: feature

#36 feature/review,comment 수정기능 추가 ,페이지 쿼리 추가/#29
  .github/CODEOWNERS
  .prettierrc
  app/src/models/commentStorage.js
  app/src/models/reviewStorage.js
  app/src/routes/commentInfo/commentInfo.ctrl.js
  app/src/routes/home/index.js
  app/src/routes/reviewInfo/reviewInfo.ctrl.js
  app/src/services/comment.js
  app/src/services/review.js
Labels: feature

#40 bugfix/review, comment 변수 오류 수정/#38
  app/src/models/commentStorage.js
  app/src/models/reviewStorage.js
  app/src/services/comment.js
  app/src/services/review.js
Labels: bugfix

#42 Feature/movie sort/#39
  app/src/models/movieStorage.js
  app/src/models/wishListStorage.js
  app/src/routes/home/index.js
  app/src/routes/movieInfo/movieInfo.ctrl.js
  app/src/services/movie.js
Labels: feature

#44 Feature/review like api/#37
  app/src/models/reviewLikeStorage.js
  app/src/routes/home/index.js
  app/src/routes/reviewLike/reviewLike.ctrl.js
  app/src/services/reviewLike.js
Labels: feature

#47 bugfix/무비,댓글,좋아요,리뷰,pr리뷰어설정 버그픽스/#39
  .github/CODEOWNERS
  app/src/models/movieStorage.js
  app/src/models/reviewLikeStorage.js
  app/src/services/comment.js
  app/src/services/movie.js
  app/src/services/wishList.js
Labels: bugfix

#50 Setting/cors미들웨어 설치 + 도커파일, 도커컴포즈파일 생성/#48
  Dockerfile
  app/app.js
  app/package-lock.json
  app/package.json
  docker-compose.yml
  package-lock.json
Labels: bugfix, setting

#51 modify/cors옵션설정/#48
  app/app.js
Labels: modify

#56 Setting/name setting/#53
  app/src/routes/comment/comment.ctrl.js
  app/src/routes/home/index.js
  app/src/routes/movie/movie.ctrl.js
  app/src/routes/review/review.ctrl.js
  app/src/routes/reviewLike/reviewLike.ctrl.js
  app/src/routes/wishList/wishList.ctrl.js
  app/src/services/commentService.js
  app/src/services/movieService.js
  app/src/services/reviewLikeService.js
  app/src/services/reviewService.js
  app/src/services/wishListService.js
Labels: setting

#58 Setting/cors/#48
  app/app.js
  app/src/routes/movieInfo/movieInfo.ctrl.js
Labels: bugfix, modify, setting

#65 Feature/signup/#55
  app/package-lock.json
  app/package.json
  app/src/models/userStorage.js
  app/src/routes/home/index.js
  app/src/routes/user/user.ctrl.js
  app/src/services/userService.js
Labels: feature

#66 Feature/movie search/#57
  app/src/common/utils/stringUtils.js
  app/src/models/movieStorage.js
  app/src/routes/movie/movie.ctrl.js
  app/src/routes/wishList/wishList.ctrl.js
  app/src/services/movieService.js
  app/src/services/wishListService.js
Labels: feature, modify

#68 refactor/콘솔지우기/#67
  app/src/common/utils/stringUtils.js
Labels: bugfix, refactor

#70 feature/wishlist-movieinfo가져오기구현/#69
  app/src/models/wishListStorage.js
  app/src/routes/home/index.js
  app/src/routes/wishList/wishList.ctrl.js
  app/src/services/wishListService.js
Labels: feature

#71 Refactor/response값 refatoring/#59
  app/package-lock.json
  app/package.json
  app/src/models/commentStorage.js
  app/src/models/reviewLikeStorage.js
  app/src/routes/comment/comment.ctrl.js
  app/src/routes/review/review.ctrl.js
  app/src/routes/reviewLike/reviewLike.ctrl.js
  app/src/services/commentService.js
  app/src/services/reviewLikeService.js
  app/src/services/reviewService.js
Labels: refactor

#74 Refactor/response refatoring/#59
  app/src/models/reviewLikeStorage.js
  app/src/routes/home/index.js
  app/src/routes/user/user.ctrl.js
  app/src/services/reviewLikeService.js
  app/src/services/reviewService.js
Labels: bugfix, refactor

#82 Modify/signup/#81
  app/src/models/userStorage.js
  app/src/services/userService.js
Labels: modify

#79 Feature/duplicate check/#77
  app/src/routes/home/index.js
  app/src/routes/user/user.ctrl.js
  app/src/services/userService.js
Labels: feature

#78 Feature/validation feature/#75
  app/src/routes/comment/commentValidation.js
  app/src/routes/home/index.js
  app/src/routes/movie/movieValidation.js
  app/src/routes/review/reviewValidation.js
  app/src/routes/reviewLike/reviewLikeValidation.js
  app/src/routes/user/userValidation.js
  app/src/routes/wishList/wishListValidation.js
  app/src/services/commentService.js
  app/src/services/movieService.js
  app/src/services/reviewLikeService.js
  app/src/services/reviewService.js
  app/src/services/wishListService.js
Labels: feature

#85 Feature/chack access token/#80
  app/src/auth/auth.ctrl.js
  app/src/auth/authService.js
  app/src/routes/home/index.js
  app/src/services/movieService.js
Labels: feature

#87 Feature/user update/#83
  app/src/models/userStorage.js
  app/src/routes/home/index.js
  app/src/routes/user/user.ctrl.js
  app/src/services/userService.js
Labels: feature

#84 setting/validation 파일 구조 수정/#75
  app/src/routes/home/index.js
  app/src/routes/validation/commentValidation.js
  app/src/routes/validation/movieValidation.js
  app/src/routes/validation/reviewLikeValidation.js
  app/src/routes/validation/reviewValidation.js
  app/src/routes/validation/userValidation.js
  app/src/routes/validation/wishListValidation.js
  app/src/services/commentService.js
  app/src/services/reviewService.js
Labels: setting

#90 Bugfix/cors options/#88
  app/app.js
Labels: bugfix, deploy, refactor

#92 Feature/validation feature/#75
  app/src/routes/validation/commentValidation.js
  app/src/routes/validation/movieValidation.js
  app/src/routes/validation/reviewLikeValidation.js
  app/src/routes/validation/reviewValidation.js
  app/src/routes/validation/userValidation.js
  app/src/routes/validation/wishListValidation.js
Labels: modify

#93 Feature/get user info/#86
  app/src/routes/home/index.js
  app/src/routes/user/user.ctrl.js
  app/src/routes/validation/userValidation.js
  app/src/services/userService.js
Labels: feature

#97 Feature/validation feature/#75
  app/src/routes/validation/commentValidation.js
  app/src/routes/validation/reviewValidation.js
Labels: bugfix

#98 bugfix/cors옵션추가/#88
  app/app.js
Labels: bugfix
